### ISSUE TITLE
Apostrophes are things

### ISSUE THREAD

**Issue by jsumners** [marko-js/marko-tmbundle#1]
A single quote in a contraction doesn't end correctly. At least not when used in IntelliJ IDEA.

![2016-03-16_18-11-23](https://cloud.githubusercontent.com/assets/321201/13830468/35c0927e-eba3-11e5-8548-105f5ac28bf0.png)

**Comment by patrick-steele-idem** [comment]
Thanks for letting me know. Taking a look now. I'll update soon.

**Comment by patrick-steele-idem** [comment]
Hey @jsumners, I am not able to reproduce the problem in TextMate or Atom using this TextMate bundle file. Are you sure IntelliJ is configured correctly to use the TextMate bundle for Marko?

**Comment by jsumners** [comment]
Pretty sure. I just cloned the repository, installed Jetbrains's TextMate bundle plugin, and added the bundle. I did change the "TextMate Color Scheme" column to Darcula:

![2016-03-16_18-33-14](https://cloud.githubusercontent.com/assets/321201/13830809/95470c62-eba5-11e5-9de0-98146eeaf9da.png)

**Comment by patrick-steele-idem** [comment]
Ok, let me try WebStorm.

**Comment by patrick-steele-idem** [comment]
I just tried with WebStorm and I am not seeing the issue. Did you try restarting WebStorm? I found that when I first installed the Marko TextMate bundle into WebStorm the syntax highlighting wasn't working as expected.

**Comment by jsumners** [comment]
Just tried it. Same thing :-/

I'm using actual IDEA 15 not WebStorm. Must be something local or to do with IDEA (which doesn't make much sense).
