### ISSUE TITLE
Unreadable texts with Dracula color scheme

### ISSUE THREAD

**Issue by Allain55** [marko-js/marko-tmbundle#11]
I've installed this on PhpStorm 2017.3.3 with Dracula color scheme in editor and the texts has white background but black with focus which is unreadable. After restarting PhpStorm everything is ok, but when I type something in a marko file, it changes to this:
![textmate](https://user-images.githubusercontent.com/8275891/35347759-60ade0fe-0136-11e8-9fc9-23dd6b246cc7.PNG)

**Comment by austin-rausch** [comment]
https://www.jetbrains.com/help/phpstorm/textmate-bundles.html
You can change the mapping of text-mate themes to jetbrains themes. The default is 'Mac Classic' which is why you have that view.  You change it in the same spot you import the textmate bundle.

**Comment by Allain55** [comment]
I've tried that, there is no more Mac Classic (see the attached picture)
After a PHPStorm restart everything is fine but after some time the same effect happens (picture above)

![kep](https://user-images.githubusercontent.com/8275891/35884093-c00002d2-0b89-11e8-8e3c-cf7f14cc4cd3.png)

**Comment by icelord2** [comment]
On linux the above worked but on Windows the suggested fix doesnt work

**Comment by DylanPiercey** [comment]
The TM bundle has been rewritten and so I'm not sure the same issue applies.
