### ISSUE TITLE
Grammar no longer compiles for Linguist

### ISSUE THREAD

**Issue by lildude** [marko-js/marko-tmbundle#15]
👋 from the github/linguist repo; that one used for all syntax highlighting on GitHub.com 😁.

Linguist uses your grammar for syntax highlighting of Marko and I've just noticed that this https://github.com/marko-js/marko-tmbundle/commit/8315efd866f2379044d6e06911af655b1fa88ca7 change in which you changed from using the plist format to JSON results in our compiler no longer recognising your repo has a grammar:

```
[...]
Deregistering submodule: vendor/grammars/marko-tmbundle
Cleared directory 'vendor/grammars/marko-tmbundle'
Submodule 'vendor/grammars/marko-tmbundle' (https://github.com/marko-js/marko-tmbundle) unregistered for path 'vendor/grammars/marko-tmbundle'
rm 'vendor/grammars/marko-tmbundle'
Registering new submodule: https://github.com/marko-js/marko-tmbundle.git
Reactivating local git directory for submodule 'vendor/grammars/marko-tmbundle'
source 'vendor/grammars/marko-tmbundle' contains no grammar files   <----- 💥 Whoops
```

This is happening because in that commit you renamed and changed the format of the file, however the directory is no longer correct because JSON grammars are expected to be served out of a `syntaxes` or `grammars` directory (depending on the editor), not a `Syntaxes` (uppercase S) directory.

You can see all the expected locations for grammars based on extension [here](https://github.com/github/linguist/blob/9703d62f12e35c006d283ddbcf04481fdefefff5/tools/grammars/compiler/loader.go#L119-L128).

I'm in the process of making a new release so if you're quick to fix this, you might just make it in to the next release (I'm building the release at about 9:30am GMT+1 tomorrow, 9 Jun 2022). If you don't, it's not a problem; I'll keep the current older plist grammar and update next time round which will be in approx 2-3 months.

**Comment by mlrawlings** [comment]
Thanks for the heads up!  Somehow this issue slipped under the radar, so I guess we'll catch you on the next release 😅
