### ISSUE TITLE
Grammar contains regex errors

### ISSUE THREAD

**Issue by lildude** [marko-js/marko-tmbundle#17]
👋 from Linguist. Our grammar compiler has detected the following regex errors in the grammar:

  - Invalid regex in grammar: `text.marko` (in `syntaxes/marko.tmLanguage.json`) contains a malformed regex (regex "`(?=[,;\]]|/>|(?<=[^>=])>[^>=]|(?`...": nothing to repeat (at offset 109))
  - Invalid regex in grammar: `text.marko` (in `syntaxes/marko.tmLanguage.json`) contains a malformed regex (regex "`(?<![a-zA-Z0-9%).<\]}]\s*)/(?:[^`...": lookbehind assertion is not fixed length (at offset 25))
  - Invalid regex in grammar: `text.marko` (in `syntaxes/marko.tmLanguage.json`) contains a malformed regex (regex "`(?=[,;\](]|/>|(?<=[^>=])>[^>=]|(`...": nothing to repeat (at offset 110))
  - Invalid regex in grammar: `text.marko` (in `syntaxes/marko.tmLanguage.json`) contains a malformed regex (regex "`(?=[,;\]]|/>|(?<=[^>=])>[^>=]|(?`...": nothing to repeat (at offset 109))

**Comment by DylanPiercey** [comment]
@lildude I believe this should be resolved after #18. Really appreciate the heads up, let me know if this looks good on your end!
