### ISSUE TITLE
Webstorm syntax highlighting

### ISSUE THREAD

**Issue by chrisblossom** [marko-js/marko-tmbundle#6]
I am unable to get ``WebStorm 2017.1 Build #WS-171.3780.79`` syntax highlighting to work. Below is a screenshot of what I am seeing.

<img width="397" alt="screen shot 2017-03-29 at 8 23 42 am" src="https://cloud.githubusercontent.com/assets/1595871/24462630/4f29b3dc-1459-11e7-9438-3dff2fa59f66.png">

Ideas?

Thank you!

**Comment by patrick-steele-idem** [comment]
It's working, but the default color scheme that WebStorm chooses for you is pretty terrible. You can customize the syntax color scheme for each WebStorm theme:

![marko-webstorm](https://cloud.githubusercontent.com/assets/978214/24463267/8ba58c28-1463-11e7-95e3-e876f01c31ac.png)

Closing issue, but let us know if you still have questions.
