### ISSUE TITLE
I clicked the Webstorm link and got directed to here. I don't think this is the plugin for Webstorm.

### ISSUE THREAD

**Issue by LeiLiTroy** [marko-js/marko-tmbundle#7]

**Comment by doomedramen** [comment]
Same, Support for my IDE is pretty important for me to switch to another framework.

**Comment by doomedramen** [comment]
Found: https://github.com/marko-js/marko-tmbundle/pull/3/commits/c158368ab334fa3b08cbadb3d0930e15eb6b1bdc

**Comment by jasonmacdonald** [comment]
I so wish I had the time to write a proper language plugin for Intellij/webstorm. It pains me having to flip over to atom every time I want to edit a Marko file. The TM bundle just doesn't cut it, you lose all basic HTML syntax handling :(

**Comment by mlrawlings** [comment]
I'm going to close this.

We don't have a plugin for Webstorm, but (as mentioned above) the README has [instructions](https://github.com/marko-js/marko-tmbundle#intellij-idea--webstorm) setting up syntax highlighting in IntelliJ/Webstorm.
